### ISSUE TITLE
Bug for chromosome X and Y

### ISSUE THREAD

**Issue by HaojiaWu** [compbiolabucf/APA-Scan#5]
I found a bug on processing the chromosome X and Y. Would this be able to fix? Thanks!
```
Loading chromosomes...
Creating read coverage files for RNA-seq data...
Preparing result using RNA-seq data only
Traceback (most recent call last):
  File "/mnt/sda/SRSF7_siRNA/APA-Scan/APA-Scan2.py", line 84, in <module>
    methods.with_PAS_signal(chromosomes, input1_dir, input2_dir, s1_namelist, s2_namelist, g1_name, g2_name, output_dir, result_filename)
  File "/mnt/sda/SRSF7_siRNA/APA-Scan/methods.py", line 740, in with_PAS_signal
    bam_list, position_row = read_bamfiles(input1_dir, sample1, chrom)
  File "/mnt/sda/SRSF7_siRNA/APA-Scan/methods.py", line 99, in read_bamfiles
    position_row = [int(bam_list[i][0]) for i in range(len(bam_list))]
  File "/mnt/sda/SRSF7_siRNA/APA-Scan/methods.py", line 99, in <listcomp>
    position_row = [int(bam_list[i][0]) for i in range(len(bam_list))]
ValueError: invalid literal for int() with base 10: 'Y'
```

**Comment by HaojiaWu** [comment]
I see what the problem is and have fixed it.
