### ISSUE TITLE
error at end of run

### ISSUE THREAD

**Issue by RomoL2** [compbiolabucf/APA-Scan#9]
Hello, and thank you for this tool! I am running on a VM and it seems to run fine but then doesn't output the Group1_Vs_Group2.csv (the only file I see in the output folder is Signal_positions.csv). The output is below, this is the final error: 

File "pandas/_libs/parsers.pyx", line 557, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file

It also seems to have trouble finding samtools (the command path is /home/jupyter/bin/samtools) but I added samtools fine to my path as I have no trouble running samtools outside of APAscan.  Any thoughts? Thank you!
Lindsay

RNA-seq input 1 dir: /home/jupyter/LR-RareDisease/edit/group1
RNA-seq input 2 dir: /home/jupyter/LR-RareDisease/edit/group2
3'-end-seq input 1 dir: NULL
3'-end-seq input 2 dir: NULL
Output Dir: /home/jupyter/LR-RareDisease/edit/APAscan_output/
Annotation: hg38_Refseq.txt hg38.fa 

Loading annotation information ...
Generating read coverage files from the RNA-seq data...
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
VCGS_FAM61_190.Aligned.sortedByCoord.out.bam ...
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
WAL_OTH2419f-Dec19.Aligned.sortedByCoord.out.bam ...
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
sh: 1: /home/jupyter/LR-RareDisease/edit/samtools: not found
Preparing result using RNA-seq data only
Chrom chr1  done in  1.82 minutes
Chrom chr10  done in  0.78 minutes
Chrom chr11  done in  1.03 minutes
Chrom chr12  done in  0.93 minutes
Chrom chr13  done in  0.47 minutes
Chrom chr14  done in  0.61 minutes
Chrom chr15  done in  0.65 minutes
Chrom chr16  done in  0.73 minutes
Chrom chr17  done in  0.93 minutes
Chrom chr18  done in  0.35 minutes
Chrom chr19  done in  0.96 minutes
Chrom chr2  done in  1.35 minutes
Chrom chr20  done in  0.51 minutes
Chrom chr21  done in  0.27 minutes
Chrom chr22  done in  0.39 minutes
Chrom chr3  done in  1.06 minutes
Chrom chr4  done in  0.85 minutes
Chrom chr5  done in  0.93 minutes
Chrom chr6  done in  1.01 minutes
Chrom chr7  done in  0.93 minutes
Chrom chr8  done in  0.78 minutes
Chrom chr9  done in  0.8 minutes
Chrom chrX  done in  0.64 minutes
Chrom chrY  done in  0.09 minutes
Traceback (most recent call last):
  File "/home/jupyter/LR-RareDisease/edit/APA-Scan/APA-Scan.py", line 82, in <module>
    methods.with_PAS_signal(chromosomes, input1_dir, input2_dir, s1_namelist, s2_namelist, g1_name, g2_name, output_dir, result_filename)
  File "/home/jupyter/LR-RareDisease/edit/APA-Scan/methods.py", line 672, in with_PAS_signal
    bam_list, position_row = read_bamfiles(input1_dir, sample1, chrom)
  File "/home/jupyter/LR-RareDisease/edit/APA-Scan/methods.py", line 111, in read_bamfiles
    bam_df = pd.read_csv(os.path.join(input_dir, sample, chrom+".txt"), delimiter='\t')
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1679, in _make_engine
    return mapping[engine](f, **self.options)
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 93, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 557, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file

**Comment by RomoL2** [comment]
nevermind, I think i figured out the issue- will update if not.

**Comment by RomoL2** [comment]
Ok, yes, it is running now. FYI the code doesn't work if the samtools command isn't in the cwd. Because I'm on a VM I don't have sudo privileges and had to install samtools in /home/jupyter/bin/, but was running APA-scan from /home/jupyter/LR-RareDisease/edit so the SamtoText function wasn't working due to this line: 

cmd1 = os.path.join(cwd, "samtools")+" index "+os.path.join(input_path, bamfile)

I had to edit the methods.py to manually add the full path to samtools to make it work, which it seems to be. 

def SamtoText(input_path, bamfile, chromosomes):
    samtools_path = "/home/jupyter/bin/samtools"  # Full path to samtools

    output_dir = os.path.join(input_path, bamfile[:-4])
    os.makedirs(output_dir, exist_ok=True)

    # Run samtools index
    cmd1 = f"{samtools_path} index {os.path.join(input_path, bamfile)}"
    os.system(cmd1)

    print(bamfile, "...")
    for chrom in chromosomes:
        # View command to filter BAM by chromosome
        cmd2 = f"{samtools_path} view -b {os.path.join(input_path, bamfile)} {chrom} -o {os.path.join(output_dir, chrom + '.bam')}"
        cmd3 = f"{samtools_path} pileup {os.path.join(output_dir, chrom + '.bam')} | cut -f 2,4 > {os.path.join(output_dir, chrom + '.txt')}"
        
        # Run the commands
        os.system(cmd2)
        os.system(cmd3)

    return
